---
version: '3'
services:
  miniflux-filter:
    image: tborychowski/miniflux-filter
    container_name: miniflux-filter
    restart: unless-stopped
    environment:
      - TZ=Europe/Dublin
      - HOST=https://rss.domain.tld
      - API_KEY=<asdASD123>
      - CHECK_EVERY_S=300 # 300 seconds = 5 min
    volumes:
      #- ./logs:/app/logs
      - ./filters.yml:/app/filters.yml
